version: "3"
services:
  openresty:
    image: ik8share/openresty:1.19.3.2-alpine
    container_name: openresty_community_edition
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      #- ./lua-custom:/usr/local/openresty/nginx/lua-custom
      - ./nginx:/usr/local/openresty/nginx/conf/nginx
      - /var/www/letsencrypt:/var/www/letsencrypt
      - /etc/letsencrypt/live:/etc/letsencrypt/live
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
    ports:
      - 80:80
      - 443:443
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
  docsify:
    image: ik8share/docsify:latest
    container_name: docsify_community_edition
    volumes:
     - ./docs:/app/docs
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
    ports:
      - 3000:3000
    restart: always
    deploy:
      restart_policy:
        condition: on-failure