version: "3"
services:
  hexo:
    image: ik8share/docsify:latest
    container_name: docsify_community_edition
    volumes:
     - ./docs:/app/docs
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
    ports:
      - 80:3000
